#!/bin/sh

#rate=$(curl -sf https://api.kraken.com/0/public/Ticker?pair=BTCUSD | jq -r ".result.XXBTZUSD.c[0]")
rate=$(curl -sf https://www.bitstamp.net/api/v2/ticker/btcusd | jq -r ".last")
rate=$(LANG=C printf "%.2f" "$rate")

echo " $rate $"
